//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameServer.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exception {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exception() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameServer.Resources.Exception", typeof(Exception).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 시스템설정이 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_01 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 기본언어가 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_02 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 게임구성이 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_03 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 시작대륙ID가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_04 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 안전부활대륙ID가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_05 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 간이상점판매 슬롯 갯수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_06 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 주말출석보상아이템 ID가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_07 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 오늘의미션 카운트가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_08 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 메인장비추가옵션 최소갯수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_09 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 메인장비추가옵션 최대갯수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_10 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 크리처추가속성개수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_100 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 크리처스킬슬롯최대개수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_101 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 크리처스킬기본개방개수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_102 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 크리처합성스킬보호아이템ID가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_103 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 크리처주입경험치회수비율이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_104 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 크리처변이필요아이템ID가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_105 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 크리처추가전환결과아이템ID가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_106 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 크리처방생경험치가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_107 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 오픈7일이벤트코스튬보상필요아이템ID가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_108 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 오픈7일이벤트코스튬보상필요아이템수량이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_109 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 메인장비세련아이템ID가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_11 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 국가동맹불가시작시각이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_110 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 국가동맹불가종료시각이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_111 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 국가동맹불가시작시각이 국가동맹불가종료시각보다 높거나 같습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_112 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 국가동맹필요자금이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_113 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 국가동맹파기불가기간이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_114 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 국가초기국력이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_115 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 전직퀘스트요구영웅레벨이 유효하지 않습니다. m 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_116 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 전직퀘스트요구아이템ID가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_117 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 코스튬콜렉션활성화아이템ID가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_118 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 코스튬콜렉션셔플아이템ID가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_119 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 메인장비분해 슬롯 갯수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_12 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 코스튬콜렉션셔플아이템수량이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_120 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 금지어 타입이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_121 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [아이템 목록] 아이템 타입이 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_122 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [아이템관련] 크리쳐먹이타입아이템이 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_123 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [아이템관련] 크리쳐정수타입아이템이 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_124 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [게임구성] 탈것레벨업아이템이 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_125 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [게임구성] 탈것각성아이템이 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_126 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [게임구성] 던전소탕아이템이 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_127 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [게임구성] 해당 아이템이 소탕아이템 타입이 아닙니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_128 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [게임구성] 길드헌팅기부아이템이 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_129 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 파티멤버최대수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_13 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [게임구성] 코스튬강화아이템이 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_130 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [게임구성] 길드헌팅기부아이템보상이 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_131 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [게임구성] 길드헌팅기부아이템완료보상이 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_132 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [게임구성] 오픈7일이벤트코스튬아이템보상이 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_133 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [상태이상레벨 목록] 상태이상이 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_134 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [상태이상레벨 목록] 상태이상 소스타입이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_135 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [상태이상레벨 목록] 직업이 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_136 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [상태이상계급스킬레벨 목록] 상태이상이 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_137 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [상태이상계급스킬레벨 목록] 상태이상 소스타입이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_138 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [직업스킬레벨마스터 목록] 직업스킬마스터가 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_139 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 파티멤버로그아웃기간이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_14 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [직업스킬 목록] 직업스킬마스터가 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_140 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [직업스킬 목록] 직업이 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_141 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [직업스킬레벨 목록] 직업이 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_142 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [직업스킬레벨 목록] 직업스킬이 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_143 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [직업스킬레벨 목록] 직업스킬레벨마스터가 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_144 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [직업스킬적중 목록] 직업이 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_145 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [직업스킬적중 목록] 직업스킬이 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_146 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [직업연계스킬적중상태이상 목록] 직업이 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_147 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [직업연계스킬적중상태이상 목록] 직업스킬이 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_148 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [직업연계스킬적중상태이상 목록] 직업스킬적중이 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_149 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 파티초대생명주기가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_15 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [직업연계스킬 목록] 직업이 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_150 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [직업연계스킬 목록] 직업스킬이 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_151 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [직업연계스킬적중 목록] 직업이 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_152 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 파티가입신청생명주기가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_16 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 파티소집쿨타임이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_17 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 휴식보상필요영웅레벨이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_18 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 골드휴식보상비율이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_19 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 다이아휴식보상비율이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_20 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 채팅최대길이가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_21 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 채팅최소인터벌이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_22 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 세계채팅아이템ID가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_23 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 탈것품질업요구레벨업수량이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_24 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 장착된탈것속성가중치가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_25 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 탈것장비옵션속성갯수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_26 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 탈것장비세련아이템ID가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_27 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 탈것각성필요영웅레벨이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_28 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 탈것포션속성아이템ID가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_29 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 날개강화아이템ID가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_30 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 날개강화경험치가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_31 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 날개표시최소VIP레벨이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_32 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 최대스태미너가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_33 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 스태미너회복시간이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_34 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 카트일반속력이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_35 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 카트고속속력이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_36 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 카트고속속력기간이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_37 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 카트고속속력기간확장이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_38 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 카트가속쿨타임이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_39 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 카트가속성공율이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_40 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PVP최소영웅레벨이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_41 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 세계레벨경험치버프최소영웅레벨이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_42 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 현상금사냥꾼퀘스트최대횟수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_43 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 랭킹표시 최대카운트가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_44 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 길드랭킹표시 최대카운트가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_45 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 선물인기점수랭킹표시 최대카운트가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_46 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 선물공헌점수랭킹표시 최대카운트가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_47 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 길드 요구영웅레벨이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_48 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 길드생성 요구VIP레벨이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_49 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 길드생성 요구다이아가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_50 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 길드재가입간격시간이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_51 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 길드가입신청접수최대횟수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_52 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 길드일일신청최대횟수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_53 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 길드일일추방최대횟수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_54 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 길드초대생명주기가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_55 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 길드알림최대길이가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_56 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 길드부길드장수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_57 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 길드로드수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_58 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 길드소집생명주기가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_59 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 길드소집반경이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_60 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 길드일일목표알림쿨타임이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_61 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 기본길드주간목표ID가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_62 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 길드헌팅기부최대횟수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_63 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 계급개방메인퀘스트번호가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_64 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 날개개방영웅레벨이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_65 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 날개개방지급날개ID가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_66 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 국가소집생명주기시간이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_67 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 국가소집반경이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_68 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 국가전몬스터전투모드유지기간이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_69 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 크리처카드상점랜덤상품수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_70 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 크리처카드상점유료갱신다이아가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_71 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 가속필요이동지속시간이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_72 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 가속이동속도가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_73 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 풍광퀘스트필요메인퀘스트번호가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_74 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 몬스터그로기유지시간이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_75 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 몬스터훔치기유지시간이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_76 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 오픈선물요구영웅레벨이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_77 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 오픈7일이벤트필요메인퀘스트번호가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_78 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 현상금사냥꾼퀘스트요구영웅레벨이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_79 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 할일위탁필요VIP레벨이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_80 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 정예몬스터처치적용필요영웅레벨이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_81 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 창고필요VIP레벨이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_82 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 무료창고슬롯수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_83 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 날개기억조각장착필요영웅레벨이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_84 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 시련퀘스트슬롯카운트가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_85 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 친구최대수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_86 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 임시친구최대수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_87 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 사망기록최대수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_88 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 블랙리스트항목최대수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_89 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 축복퀘스트목록최대수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_90 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 축복퀘스트필요영웅레벨이 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_91 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 축복목록최대수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_92 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 소유유망자퀘스트목록최대수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_93 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 대상유망자퀘스트목록최대수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_95 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 크리처최대개수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_96 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 크리처응원최대개수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_97 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 크리처응원속성계수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_98 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 크리처평점계수가 유효하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Resource_LoadUserDBResources_99 {
            get {
                return ResourceManager.GetString("Resource_LoadUserDBResources_99", resourceCulture);
            }
        }
    }
}
